### Site metadata ###

title: SoFloRuby
description:  All things Ruby in South Florida - A South Florida Ruby Community

### Build settings ###

url: ""
baseurl: "/"

exclude:
  - bin/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package*.json
  - yarn.lock
  - postcss.config.js
  - purgecss.config.js
  - README.md
  - netlify.toml