### Site metadata ###

title: SoFloRuby
description:  All things Ruby in South Florida - A South Florida Ruby Community
google_analytics: G-KHB2T6H7H7

### Build settings ###

url: "https://sofloruby.org"
baseurl: "/"

permalink: /blog/:title/

exclude:
  - bin/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package*.json
  - yarn.lock
  - postcss.config.js
  - purgecss.config.js
  - README.md
  - netlify.toml